name: Label to Title change

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  label-to-title:
    runs-on: ubuntu-latest
    steps:
    - uses: pyiron/actions/label-to-title@label-to-title
